build:
	gcloud container builds submit -t gcr.io/enhanced-storm-175413/say .ls

push:
	gcloud docker -- push gcr.io/enhanced-storm-175413/say

pull:
	gcloud docker -- pull gcr.io/enhanced-storm-175413/say